// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Active wallet address — set by WalletProvider whenever the connected
// wallet changes. Sent on every request as `x-wallet-address` so RLS
// policies (is_admin_wallet, is_member_wallet) can read it.
let _activeWallet: string | null = null;
export const setActiveWallet = (addr: string | null) => {
  _activeWallet = addr;
};
export const getActiveWallet = () => _activeWallet;

const customFetch: typeof fetch = (input, init) => {
  const headers = new Headers((init as RequestInit | undefined)?.headers || {});
  if (_activeWallet) headers.set("x-wallet-address", _activeWallet);
  return fetch(input, { ...(init as RequestInit | undefined), headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customFetch,
  },
});
